server:
  port: 8888

eureka:
  instance:
    hostname: configServer
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaServer:8761/eureka/

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kbastani/spring-boot-microservice-config
#logging:
#  level:
#    org: debug
#    com: debug
